name: "Terragrunt plan STAGING"

on:
  pull_request:
    branches:
      - main
    paths:
      - "terragrunt/aws/**"
      - "terragrunt/env/staging/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/root.hcl"
      - ".github/workflows/terragrunt-plan-staging.yml"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.12.1
  TERRAGRUNT_VERSION: 0.68.6
  TF_INPUT: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terragrunt-plan-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::992382783569:role/gcds-protospace-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt plan
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "terragrunt/env/staging"
          comment-delete: "true"
          comment-title: "Staging"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
